name: Deploiement continu

on:
    workflow_call

jobs:
    push:
      if: ${{ contains(github.event.head_commit.message, '#docker')}}
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_LOGIN }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Extract Metada
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: aracode/marcelus

        - name: Setup docker buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and Push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.label }}

    compose:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Compose file send
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}            
            username: ${{ secrets.LOGIN }}
            password: ${{ secrets.PASS }}

            source: "./docker-compose.yml"
            target: "."

    pull:
      needs: [push,compose]
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Server update
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}            
            username: ${{ secrets.LOGIN }}
            password: ${{ secrets.PASS }}

            script: |
              docker pull arocode/marcelus:main
              docker-compose up -d


